import Footer from "@/components/footer/Footer";
import Navbar from "@/components/navbar/Navbar";
import QueryProvider from "@/components/query/QueryProvider";
import "./globals.css";

export const metadata = {
  title: "Next Job Finder App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-white">
        <QueryProvider>
          <Navbar />
          {children}
          <Footer />
        </QueryProvider>
      </body>
    </html>
  );
}
