"use client";

import Footer from "@/components/footer/Footer";
import Navbar from "@/components/navbar/Navbar";
import QueryProvider from "@/components/query/QueryProvider";
import { usePathname } from "next/navigation";
import { useEffect } from "react";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const metadata = {
  title: "Next Job Finder App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const path = usePathname();

  useEffect(() => {
    window.scrollTo(0, 0);
  }, [path]);
  return (
    <html lang="en">
      <body className="bg-white">
        <QueryProvider>
          <Navbar />
          {children}
          <Footer />
          <Toaster />
        </QueryProvider>
      </body>
    </html>
  );
}
